### ISSUE TITLE
Passing CC option has sent separate email instead of carbon copy.

### ISSUE THREAD

**Issue by Ashanmg** [feinoujc/Mandrill.net#102]
I have tried to send emails using the mandrill.net library and it worked fine for sending emails for a single email.
But when I tried to send an email with a **cc option** it has sent two different emails.

First I created a mandril message and added required fields.
```
var api = new MandrillApi(apiKey);
var message = new MandrillMessage();
message.FromEmail = "email from";
message.AddTo("email to");
message.Subject = "the subject";
message.AddGlobalMergeVars("body", "the body");
message.AddTo("cc email address", string.Empty, MandrillMailAddressType.Cc);

api.Messages.SendTemplateAsync(message, "email template of mandrill");
```
Has anyone faced the same issue or solved the issue like this?

**Comment by feinoujc** [comment]
It might be that you want to set `PreserveRecipients` to true

https://mandrillapp.com/api/docs/messages.html

**Comment by Ashanmg** [comment]
@feinoujc Thanks. Yes, I didn't know about the "PreserveRecipients" need to be true. After setting it as true it worked fine for me. I will close this issue.
