### ISSUE TITLE
Handlebars not working

### ISSUE THREAD

**Issue by zyofeng** [feinoujc/Mandrill.net#115]
Im using the following test:

message.AddGlobalMergeVars("profile", new { firstname = "Test" });
_mandrillApi.SendTemplateAsync(message, "template-name");

but the outbound email in mandrill is not being replaced, showing the below:
Firstname: {{profile.firstname}},

**Comment by feinoujc** [comment]
did you try setting

```cs
MergeLanguage = MandrillMessageMergeLanguage.Handlebars
```
in your message?

**Comment by zyofeng** [comment]
Yep, still not working

var notification = new Core.Mandrill.Notifications.ROIWealthBuilder.ROIWealthBuilderNotification { FirstName = "Test first name", 
LastName = "Test last name", 
Email = "test.email@email.com", 
MobileNumber = "0211234567"
}


            var message = new MandrillMessage { MergeLanguage = MandrillMessageMergeLanguage.Handlebars };
            message.AddGlobalMergeVars("profile", notification);

Template:
First Name: {{profile.firstname}}<br/>
Last Name: {{profile.lastname}}<br/>
Email: {{profile.email}}<br/>
Mobile Number: {{profile.mobilenumber}}

This is the result, for some reason only email field is merged

First Name:
Last Name:
Email: test.email@email.com
Mobile Number:

**Comment by feinoujc** [comment]
Can you try ```first_name```, ```last_name``` etc... instead? By default, the content would be converted to snakecase, as is the mandrill api convention.

You can apply ```JsonProperty``` attributes to your properties in this Notifications class if you want to change that

**Comment by zyofeng** [comment]
Thanks that's fine
One more issue, MergeVars does not seem to work for BCC email address (also you can only have one bcc recipient?), is that a bug or a design flaw with Mandrill?

**Comment by feinoujc** [comment]
try adding a `To` address of type `Bcc` and not using the BccAddress property. I think they are for different purposes

https://mandrillapp.com/api/docs/messages.JSON.html
