### ISSUE TITLE
Not working in .net core console app

### ISSUE THREAD

**Issue by ManvirDynamic** [feinoujc/Mandrill.net#121]
This is not working in .net core 2.1.1 console app. How can we at least find the error. No emails are going and no error message. How can we send Message/Email to work in scratch .net core 2.1.1 console app?

I there any demo app which uses Mandrill.net?

**Comment by feinoujc** [comment]
@ManvirDynamic Check the status like so

https://dotnetfiddle.net/PDnYsZ

If its rejected, refer to the RejectedReason for more information

**Comment by ManvirDynamic** [comment]
Thank you. It is working now.
