### ISSUE TITLE
Search function not filter by date

### ISSUE THREAD

**Issue by AkiMC** [feinoujc/Mandrill.net#187]
Hi, 
thank you in adavance for you time. 
I am using your library and I am using the Search methods to get all email in range of date from Mandrill. But, I have noticed that the filter by date does not work. 

May you give a check, please?

Regards,
Achille

**Comment by feinoujc** [comment]
I was not able to reproduce. It seems to work as expected. If you can submit a more detailed reproduction, feel free to reopen
