### ISSUE TITLE
Newtonsoft.Json Insecure Defaults

### ISSUE THREAD

**Issue by alancooper-exizent** [feinoujc/Mandrill.net#204]
The latest release uses Newtonsoft 12.0.1 which has a DoS vulnerability.
https://alephsecurity.com/vulns/aleph-2018004

This is fixed and 13.0.3, with which this package seems ot build OK with

**Comment by feinoujc** [comment]
fixed in #216

**Comment by alancooper-exizent** [comment]
Build seems to have been OK but the nuget publish steps have been skipped by CI?
