### ISSUE TITLE
WebHookSignatureHelper.VerifyWebHookSignature was not validating the signature 

### ISSUE THREAD

**Issue by BonnieSilentPartner** [feinoujc/Mandrill.net#211]
Just wanted to mention that the following function
WebHookSignatureHelper.VerifyWebHookSignature(signature, authKey, new Uri(DisplayUrl), form);
requires a Uri object.

The signature does not validate when we use a Uri, but if we use a string of the exact URL that the Mandrill webhook calls, the validation will succeed.

StringBuilder stringBuilder = new StringBuilder();
stringBuilder.Append(DisplayUrl);

not
StringBuilder stringBuilder = new StringBuilder();
stringBuilder.Append(new Uri(DisplayUrl));

I hope this helps!

**Comment by feinoujc** [comment]
I added an overload that takes a string for these cases
https://github.com/feinoujc/Mandrill.net/commit/6ab15532b8ad5f4054c3b81671fb1c83df0aff9d

**Comment by BonnieSilentPartner** [comment]
Thank you so much!
