### ISSUE TITLE
Can no longer build

### ISSUE THREAD

**Issue by ericthornton** [feinoujc/Mandrill.net#26]
I was going to help knock out some of the remaining API calls, did a sync with your master, and now I get loads and loads of errors on build. I'm guessing some prerequisites changed?

**Comment by feinoujc** [comment]
Hi Eric. Could it be the C# 6.0 stuff? what version of visual studio do you have?

**Comment by ericthornton** [comment]
2013 Ultimate

**Comment by feinoujc** [comment]
Yeah, its the Roslyn compiler/C# 6 stuff then. probably the "easiest" thing would be install visual studio 2015. 

[There are some other options](https://social.msdn.microsoft.com/Forums/en-US/49ba9a67-d26a-4b21-80ef-caeb081b878e/will-c-60-ever-be-supported-by-vs-2013?forum=roslyn) but I don't have visual studio 2013 to verify this.
