### ISSUE TITLE
Error setting value to 'FirstSentAt' when getting Subaccount Info

### ISSUE THREAD

**Issue by davidoliveira** [feinoujc/Mandrill.net#33]
Hi,

I found an error, when I'm trying to get info account like this:

var infoSubaccount = api.Subaccounts.Info(ID_ACCOUNT);

An exception is thrown: {"Error setting value to 'FirstSentAt' on 'Mandrill.Model.MandrillSubaccountInfo'."}

With Fiddler, I can look the Mandrill API response and the returned value of *first_sent_at*  is:
,"sent_total":297,"first_sent_at":"2015-03-28 19:12:01.97852","hourly_quota":312,

Thanks.
Regards,
David

**Comment by feinoujc** [comment]
Hi David, 

The data type was wrong on that property. thanks for reporting this.
this is fixed in v2.1.2 and its up in nuget

**Comment by davidoliveira** [comment]
Hi Joe,
Thanks a lot for your quickly fix.
