### ISSUE TITLE
How to schedule a template?

### ISSUE THREAD

**Issue by vickyrathee** [feinoujc/Mandrill.net#46]
Is there a way i can schedule a template email using mandrill.net ?

```
var client = new MandrillApi("key");

var message = new MandrillMessage();
message.AddTo("email@domain.com");
message.FromEmail = "my-email@domain.com";
Messages.SendTemplate(message, "test")

message.AddGlobalMergeVars("key", "something-here");
client.Messages.SendTemplate(message, "template-slug");
```

Right now I'm using above to send the email, is there a way i can schedule it some time later. For .eg

```
client.Messages.ScheduleTemplate(message, "template-slug", DateTime.now.addDays(2));
```

**Comment by feinoujc** [comment]
@vickyrathee you should be able to use the `sendAtUtc` parameter for sending mail at a certain time

```cs
client.Messages.SendTemplate(message, "template-slug", sendAtUtc:myScheduleDateTimeInUtc);
```

[api docs](https://mandrillapp.com/api/docs/messages.JSON.html#method=send-template)

Does that work?

**Comment by vickyrathee** [comment]
Thanks @feinoujc for pointing out, i will test this and confirm.

**Comment by feinoujc** [comment]
Let me know if you have any difficulties @vickyrathee
