### ISSUE TITLE
Unable to change BaseUrl: Mandrill TSL uses port 465

### ISSUE THREAD

**Issue by WizX20** [feinoujc/Mandrill.net#54]
In Mandrill.net/src/Mandrill.net/MandrillRequest.cs the base url is hard coded:
_protected static readonly Uri BaseUrl = new Uri("https://mandrillapp.com/api/1.0/");_

Please make this URL configurable by a config or possible to override. The reason why I want to change this is because Mandrill uses port 465 for TLS/SSL: See [Mandrill Docs](https://mandrill.zendesk.com/hc/en-us/articles/205582177-Does-Mandrill-support-SSL-). This is not specified in the URL thus making the CreateHttpWebRequest(requestUri) use the default port 587.

To be honest I think this URL should not be hard coded at all. For example, use the ConfigurationManager.AppSettings[KEY] to check the web.config for the URL and use that when available.

**Comment by WizX20** [comment]
Ok, seems you need to enable the security protocols. So right before you do the request (send the message) I added:
```
System.Net.ServicePointManager.SecurityProtocol = 
                        System.Net.SecurityProtocolType.Tls | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
```

And then it works fine.

**Comment by feinoujc** [comment]
I like the idea of adding an extensibility point to pass in a custom url, I agree it probably should be hardcoded

**Comment by feinoujc** [comment]
BTW, it looks like that's the default SecurityProtocol flags value when running .NET 4.6.1. Not sure about .net core (does ServicePointManager even exist?)

http://stackoverflow.com/questions/35585963/what-is-the-default-servicepointmanager-securityprotocol-value-in-net-4-6-1/35586124
