### ISSUE TITLE
duplicate mails

### ISSUE THREAD

**Issue by isabal28** [feinoujc/Mandrill.net#59]
I have used that library for sending abandoned cart mails but there is a problem that mandrill sends mail as many as number of the item in basket.   

mergeLanguage = handlebars

is there anyone who can help me ?

**Comment by feinoujc** [comment]
Hi @isabal28, no I have not seen this issue before. Have you looked at the [api logs](https://mandrill.zendesk.com/hc/en-us/articles/213530577-SMTP-Troubleshooting-Tips) to see how many recipients you are sending?

**Comment by feinoujc** [comment]
closing this for now @isabal28 let me know if you have any more information
