### ISSUE TITLE
Mandrill Username?

### ISSUE THREAD

**Issue by mischiefgithub** [feinoujc/Mandrill.net#63]
I have this working on a dev box but not sure how it works without a mandrill username?
I also assume that it uses SSL and smpt.mandrillapp.com on port 587

**Comment by feinoujc** [comment]
@mischiefgithub  this uses the api and operates differently then SMTP

docs here: https://mandrillapp.com/api/docs/

Does that help?

**Comment by mischiefgithub** [comment]
OK that makes sense.  It was working but I did not understand the difference when I looked at the API logs in the Mandrill admin.  Thanks for the reply.
