### ISSUE TITLE
Getting message event

### ISSUE THREAD

**Issue by saboehnke** [feinoujc/Mandrill.net#66]
Is there a way for me to grab the message events that occurred inside of the function that actually sends the email? I get the response there for each email that is sent out but I need to be able to grab the message events for each email there as well so I can keep track of the time the message was actually sent out vs. when I tried to send it out.

**Comment by feinoujc** [comment]
You could capture the message id that is returned in the array of  `MandrillSendMessageResponse` objects that are returned and then get the [info](https://github.com/feinoujc/Mandrill.net/blob/master/src/Mandrill.net/MandrillMessagesApi.cs#L126) back from mandrill that should include that information. Would that work?

**Comment by saboehnke** [comment]
Yes that seems to be what I am looking for. Can you give me an example of getting the info like you suggested once I have the message id?

**Comment by saboehnke** [comment]
Maybe I am missing something. I am trying to get the info like this: 

`var response = api.Messages.Send(message);
 var info = api.WebHooks.InfoAsync(Convert.ToInt32(response[0].Id));`

but that will not work because the response's id is not an integer value. It has characters in it as well.

**Comment by saboehnke** [comment]
Ah I changed it to use api.Messages instead of WebHooks. Sorry about that. Thanks!

**Comment by feinoujc** [comment]
According to the docs, `ts` should be 
>the Unix timestamp from when this message was sent

https://mandrillapp.com/api/docs/messages.JSON.html#method=info

**Comment by saboehnke** [comment]
Great thank you!
