### ISSUE TITLE
Template Sending out Multiple Emails

### ISSUE THREAD

**Issue by janessaallen** [feinoujc/Mandrill.net#68]
Hi,

I'm using your wrapper and trying to send out (via one API call) multiple emails utilizing receipt merge variables, but having no luck.

From the below, you can see I'm sending in a list of customer leads and trying to customize the body of the template email by recipient. However, only the last lead information is sent. 

Do you know why it is disregarding the for loop of recipient merge variables? TIA!

    public static async Task<object> SendMonthlyReminder(List<CallCenterLeadModel> leads, string 
     template)
            {
      MandrillApi api = new MandrillApi(apiKey);
        var mandrillMessage = new MandrillMessage();
             mandrillMessage.FromEmail = fromEmail;
              mandrillMessage.ReplyTo = replyToEmail;

          
            foreach (var lead in leads)
            {
                mandrillMessage.AddTo(lead.Account.Email);

                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "AEMAIL", lead.Account.Email ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "NAME", lead.Account.Name ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "AREA", lead.Account.Area.Name ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "DATE", lead.DateSent.ToShortDateString());

                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "FNAME", lead.Profile.FirstName ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "LNAME", lead.Profile.LastName ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "RESIDENTNAME", lead.Profile.ResidentFirstName + " " + lead.Profile.ResidentLastName ?? "");
                mandrillMessage.AddRcptMergeVars(lead.Account.Email, "SOURCE", lead.Source ?? "");

            }

            mandrillMessage.AutoHtml = true;
            mandrillMessage.PreserveRecipients = false;

            var sendAt = DateTime.Now.ToUniversalTime();
            var result = await api.Messages.SendTemplateAsync(mandrillMessage, template, null, true, null, sendAt);
            return result;
    }

**Comment by feinoujc** [comment]
hi @janessaallen, I'm not able to reproduce this. Are you still experiencing this issue? What are you looking at to determine that it is not sending all the emails? mandrill logs? the mandrill dashboard?
