### ISSUE TITLE
How to read response and error response from API integration

### ISSUE THREAD

**Issue by vijay-pratap-singh** [feinoujc/Mandrill.net#69]
Hi Team,

We are integrating the mandrill API for sending the mail and using the below code for the same.
Here how can I read the successful response and error response. Here in case of error it is not going to catch block, if I pass the invalid API key.

Please share the demo code, if you have any.

try
            {
                var api = new MandrillApi("0xxxxxxxxxxxxxxxxxxQ");
                var message = new MandrillMessage("vijaypratap.singh@clariontechnologies.co.in", "vijaypratap.singh@clariontechnologies.co.in",
                                "hello mandrill!", "...how are you?");
                var result = api.Messages.SendAsync(message);

                IList<MandrillSendMessageResponse> response = result.Result;
            }
            catch (WebException ex)
            {
             }

Thanks,

**Comment by feinoujc** [comment]
hi @vijay-pratap-singh  try catching a MandrillException

**Comment by vijay-pratap-singh** [comment]
Hi, @feinoujc , Thanks for the reply.

Here issue is that, If I pass the wrong API key, it keeps throwing the exception on line:
IList<MandrillSendMessageResponse> response = result.Result;

And do not goes to Catch block.

Any idea? It gives in details that there are one or more errors.

Thanks!

**Comment by feinoujc** [comment]
I think this is because you are running async code synchronously (which I don't recommend). It's throwing an `AggregateException` so you'd have to catch that type, or use async/await

**Comment by feinoujc** [comment]
the root issue here is you appear to want to run async code synchronously. if you really need to run synchronously, you can downgrade to version 3.3.0 which is the last version to support non-async methods 
https://www.nuget.org/packages/Mandrill.net/3.3.0

```csharp
var result = api.Messages.Send(message);
```
 hope that helps
