### ISSUE TITLE
Error : Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}

### ISSUE THREAD

**Issue by skomsai** [feinoujc/Mandrill.net#70]
Hello,

I had tried to implement this code but mail not sent . 

the result have like this
result = Id = 21, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

Please find the code below:
 
var api = new MandrillApi("01d3e3f0ccb9a6acbb388d735b89e105-us16");
            var message = new MandrillMessage("sandeep@nextgenesolutions.com", "rpsingh@nextgenesolutions.com",
                            "hello mandrill!", "...how are you?");
            //var result = await api.Messages.SendAsync(message);
            var result = System.Threading.Tasks.Task.Run(async () => await api.Messages.SendAsync(message));

Please resolve it as soon as possible..

**Comment by feinoujc** [comment]
Your result is a `Task` because you are trying to use `Task.Run` here. you should just use async await if possible

```csharp
var result = await api.Messages.SendAsync(message);
```

if you need to run synchronously, you can downgrade to version 3.3.0 which is the last version to support non-async methods 
https://www.nuget.org/packages/Mandrill.net/3.3.0

```csharp
var result = api.Messages.Send(message);
```
