### ISSUE TITLE
How to add multiple recipients

### ISSUE THREAD

**Issue by bobby5300** [feinoujc/Mandrill.net#72]
Hi Team,

can u share me sample code to send multiple receptions using API

**Comment by feinoujc** [comment]
Hi @bobby5300 

you could just call `message.AddTo(...)` multiple times, or you could construct a `List<MandrillMailAddress>` yourself and assign it to your message

```cs
var message = new MandrillMessage
{
     Subject = "test",
     To = new List<MandrillMailAddress>()
     {
          new MandrillMailAddress("test1@example.com"),
          new MandrillMailAddress("test2@example.com")
          // etc....
     },
     Text = "This is a test"
}
```
