### ISSUE TITLE
How to send different messages to same receipient?

### ISSUE THREAD

**Issue by vickyrathee** [feinoujc/Mandrill.net#80]
I am looking for a way to send different/same messages to the list of receipeint. But my code is sending the same message only instead the different message from the List. I think due to `AddRcptMergeVars` which is merging the value based on email_id , while the email may be twice or more times in the list. Is there any way I can use this to send my same/different messages using single call. I can send using foreach, but that's 100 of calls to send separate message to each individual. So looking for a way to do this in batch using template and mergevars .

For example

```
internal async Task<IList<MandrillSendMessageResponse>> EmailAsync(List<Messages> messages)
        {
            var message = new MandrillMessage
            {
                FromEmail = "from id",            
                PreserveRecipients = false
            };

            foreach (var email in messages)
            {
                MandrillMailAddress address = new MandrillMailAddress
                {
                    Type = MandrillMailAddressType.To,
                    Email = email.to
                };
                message.To.Add(address);

                message.AddRcptMergeVars(email.to, "Subject", email.subject);
                message.AddRcptMergeVars(email.to, "Body", email.body);
            }
            var result = await GetMandrillClient().Messages.SendTemplateAsync(message, "my-template");
            return result;
        }
```

![image](https://user-images.githubusercontent.com/6106479/41909739-6fe94494-7965-11e8-8863-8908f1d114a2.png)

**Comment by feinoujc** [comment]
@vickyrathee as far as I can tell, the mandrill api doesn't support this. In the docs for `merge_vars` it says:

>rcpt: the email address of the  recipient that the merge variables should apply to.                                                                                 required

https://mandrillapp.com/api/docs/messages.JSON.html

So I think it uses the email address internally to apply the merge vars

**Comment by vickyrathee** [comment]
@feinoujc Yes, I think. I'd need to send these message one-by-one then
