### ISSUE TITLE
Add multiple BCC Adresses

### ISSUE THREAD

**Issue by cooxkie** [feinoujc/Mandrill.net#82]
Hi,

Is it possible to use your wrapper in orderto send email with multiple BCC adresses?
As I know, message.BccAddress is only for one address...

Please tell me, if I mistake

Regards

Eric

**Comment by feinoujc** [comment]
@cooxkie yes, I think it is possible using the `To` list, see here https://stackoverflow.com/questions/18211868/send-email-via-the-mandrill-api-containing-multiple-bcc-addresses

does that help?

**Comment by feinoujc** [comment]
@cooxkie please reopen if this didn't answer your question
