### ISSUE TITLE
HttpClient in MandrillRequest needs to be a singleton

### ISSUE THREAD

**Issue by jefflafay** [feinoujc/Mandrill.net#83]
It's best practice to use a HttpClient singleton in C# because it will hang on to connections. I have an API (asp.net core) running on azure and it keeps going down every time mandrill goes down this week. It's eating up connections and making my application unresponsive. Using a singleton could greatly help performance.

Here are a few links on the topic, the first being directly from microsoft:

[https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#create-and-initialize-httpclient](url)

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by feinoujc** [comment]
@jefflafay is the API creating a new MandrillApi instance on every request? Ideally, that could be done once during the Startup and register the interfaces (IMandrillMessagesApi, etc..) in the container as singletons. 


```cs
var api = new MandrillApi("YOUR_API_KEY_GOES_HERE");
services.AddSingleton<IMandrillMessagesApi>(api.Messages);
```

**Comment by jefflafay** [comment]
It was not being done and that certainly is a solution. You may want to include in any getting started documentation that the api client should be used as a singleton because of the HttpClient. Ideally, you would want to make it a singleton within the library so other's don't run into the same issue that we ran into. It's best practice for .net development.

**Comment by feinoujc** [comment]
Maybe the _best_ solution is to allow injection of the HttpClientFactory https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

because with a singleton (like above) your API would not survive a DNS change

I think adding docs is a good call for now

**Comment by jefflafay** [comment]
Absolutely agree with the factory! That's what I use for other clients in my application but I thought that your library also target full framework or standard. I could be wrong but the factory may only be available in core.

Thanks for your help with the matter.

**Comment by feinoujc** [comment]
note added in https://github.com/feinoujc/Mandrill.net/blob/master/README.md#service-registration
