### ISSUE TITLE
Newtonsoft dependency

### ISSUE THREAD

**Issue by richardhauer** [feinoujc/Mandrill.net#87]
The current version of the API requires version 12 of Newtonsoft.Json but it's not apparent that the APIs actually rely on any of the updated aspects of this library.

It would be better if the dependency requirement was the lowest supported version of the library rather than the highest.  Under the current model we cannot update beyond v5 because we have other libraries that must use Newtonsoft.Json v11 (Azure Fn Apps).

**Comment by feinoujc** [comment]
Hi Richard, the latest version is using the `NamingStrategy` support that was added to the `StringEnumConverter` which is only in v12

**Comment by richardhauer** [comment]
In v11 there is equivalent functionality as can be seen in the diff on commit `b490a29`.  The change to v12 did not introduce any new features on your part, but forcing people to use v12 makes it impossible to use this library in any Azure Function.  Please reconsider this change.
