### ISSUE TITLE
Issue null variables and boolean variables

### ISSUE THREAD

**Issue by morfragen** [feinoujc/Mandrill.net#88]
Hi!
There is an issue about this:
I call:
 var result = await mandrillApi.Messages.SendTemplateAsync(message, "ToVault", contentList, true, "Main Pool");
The message is "sent" as I see in "result" but in mandrill dashboard nothing happens and i don´t get the email message in my inbox.
I test using Postman and i realize that:
The code sent by me that works is like:

"message": {
        "from_email": "E-desk@example.com",
        "subject": "Surprise!",
        "return_path_domain": "null",
        "to": [
            {
                "email": "morfragen@gmail.com",
                "name": "Super Vault",
                "type": "to"
            }
        ],"merge": "true"
  }

With the above code it works and I get an email in my inbox, mandrill dashboard shows that message.

But when i call  var result = await mandrillApi.Messages.SendTemplateAsync(message, "ToVault", contentList, true, "Main Pool");
check the API log in mandrill and the request is like:

"message": {
        "from_email": "E-desk@example.com",
        "subject": "Surprise!",
        "to": [
            {
                "email": "morfragen@gmail.com",
                "name": "Super Vault",
                "type": "to"
            }
        ],"merge": true
  }

The Issue here is:

1.- The boolean vars appear like **true** or **false** and not like **"true"** or **"false"**
2.- The vars that have assigned "null" don´t show in the request.

Those things make the email message is not sent.

Could you help me please?

**Comment by feinoujc** [comment]
I can't reproduce this issue. Are you still experiencing this?
